resource_group_name    = "function-app-test-rg"
source_function_dir    = "./functions"
artifact_output_path   = "functions.zip"
storage_account_name   = "functionsapptestsa01"
function_app_name      = "dev-func-app-test01"
storage_container_name = "function-app-test01"
